// Benchmark/stack2-mern/frontend/src/pages/BoardView.jsx
import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { boardAPI, listAPI, cardAPI } from '../services/api';
import './BoardView.css';

function BoardView() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [board, setBoard] = useState(null);
  const [lists, setLists] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [showListModal, setShowListModal] = useState(false);
  const [showCardModal, setShowCardModal] = useState(false);
  const [selectedListId, setSelectedListId] = useState(null);
  const [newList, setNewList] = useState({ title: '' });
  const [newCard, setNewCard] = useState({ title: '', description: '' });

  useEffect(() => {
    fetchBoard();
  }, [id]);

  const fetchBoard = async () => {
    try {
      setLoading(true);
      const response = await boardAPI.getOne(id);
      setBoard(response.data);
      setLists(response.data.lists || []);
      setError(null);
    } catch (err) {
      console.error('Error fetching board:', err);
      setError('Failed to load board');
    } finally {
      setLoading(false);
    }
  };

  const handleCreateList = async (e) => {
    e.preventDefault();

    if (!newList.title.trim()) {
      alert('Please enter a list title');
      return;
    }

    try {
      const response = await listAPI.create(id, {
        title: newList.title,
        position: lists.length
      });
      setLists([...lists, { ...response.data, cards: [] }]);
      setNewList({ title: '' });
      setShowListModal(false);
    } catch (err) {
      console.error('Error creating list:', err);
      alert('Failed to create list');
    }
  };

  const handleDeleteList = async (listId, e) => {
    e.stopPropagation();

    if (!confirm('Are you sure you want to delete this list and all its cards?')) {
      return;
    }

    try {
      await listAPI.delete(listId);
      setLists(lists.filter(list => list._id !== listId));
    } catch (err) {
      console.error('Error deleting list:', err);
      alert('Failed to delete list');
    }
  };

  const openCardModal = (listId) => {
    setSelectedListId(listId);
    setShowCardModal(true);
  };

  const handleCreateCard = async (e) => {
    e.preventDefault();

    if (!newCard.title.trim()) {
      alert('Please enter a card title');
      return;
    }

    try {
      const list = lists.find(l => l._id === selectedListId);
      const cardCount = list?.cards?.length || 0;

      const response = await cardAPI.create(selectedListId, {
        title: newCard.title,
        description: newCard.description,
        position: cardCount
      });

      setLists(lists.map(list => {
        if (list._id === selectedListId) {
          return {
            ...list,
            cards: [...(list.cards || []), response.data]
          };
        }
        return list;
      }));

      setNewCard({ title: '', description: '' });
      setShowCardModal(false);
      setSelectedListId(null);
    } catch (err) {
      console.error('Error creating card:', err);
      alert('Failed to create card');
    }
  };

  const handleDeleteCard = async (listId, cardId, e) => {
    e.stopPropagation();

    if (!confirm('Are you sure you want to delete this card?')) {
      return;
    }

    try {
      await cardAPI.delete(cardId);
      setLists(lists.map(list => {
        if (list._id === listId) {
          return {
            ...list,
            cards: list.cards.filter(card => card._id !== cardId)
          };
        }
        return list;
      }));
    } catch (err) {
      console.error('Error deleting card:', err);
      alert('Failed to delete card');
    }
  };

  if (loading) return <div className="loading">Loading board...</div>;
  if (error) return <div className="error">{error}</div>;
  if (!board) return <div className="error">Board not found</div>;

  return (
    <div className="board-view-container">
      <div className="board-view-header">
        <button onClick={() => navigate('/')} className="btn btn-back">
          ← Back to Boards
        </button>
        <h2>{board.title}</h2>
        {board.description && <p className="board-description">{board.description}</p>}
      </div>

      <div className="lists-container">
        {lists.map(list => (
          <div key={list._id} className="list">
            <div className="list-header">
              <h3>{list.title}</h3>
              <button
                onClick={(e) => handleDeleteList(list._id, e)}
                className="btn-delete-list"
                title="Delete list"
              >
                🗑️
              </button>
            </div>

            <div className="cards-container">
              {list.cards && list.cards.map(card => (
                <div key={card._id} className="card">
                  <h4>{card.title}</h4>
                  {card.description && (
                    <p className="card-description">{card.description}</p>
                  )}
                  <button
                    onClick={(e) => handleDeleteCard(list._id, card._id, e)}
                    className="btn-delete-card"
                    title="Delete card"
                  >
                    ✕
                  </button>
                </div>
              ))}
            </div>

            <button
              onClick={() => openCardModal(list._id)}
              className="btn btn-add-card"
            >
              ➕ Add Card
            </button>
          </div>
        ))}

        <div className="list list-add">
          <button onClick={() => setShowListModal(true)} className="btn btn-add-list">
            ➕ Add List
          </button>
        </div>
      </div>

      {/* Create List Modal */}
      {showListModal && (
        <div className="modal-overlay" onClick={() => setShowListModal(false)}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <h2>Create New List</h2>
            <form onSubmit={handleCreateList}>
              <div className="form-group">
                <label htmlFor="list-title">List Title *</label>
                <input
                  type="text"
                  id="list-title"
                  value={newList.title}
                  onChange={(e) => setNewList({ title: e.target.value })}
                  placeholder="Enter list title"
                  autoFocus
                />
              </div>

              <div className="modal-buttons">
                <button type="button" onClick={() => setShowListModal(false)} className="btn btn-secondary">
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary">
                  Create List
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Create Card Modal */}
      {showCardModal && (
        <div className="modal-overlay" onClick={() => setShowCardModal(false)}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <h2>Create New Card</h2>
            <form onSubmit={handleCreateCard}>
              <div className="form-group">
                <label htmlFor="card-title">Card Title *</label>
                <input
                  type="text"
                  id="card-title"
                  value={newCard.title}
                  onChange={(e) => setNewCard({ ...newCard, title: e.target.value })}
                  placeholder="Enter card title"
                  autoFocus
                />
              </div>

              <div className="form-group">
                <label htmlFor="card-description">Description</label>
                <textarea
                  id="card-description"
                  value={newCard.description}
                  onChange={(e) => setNewCard({ ...newCard, description: e.target.value })}
                  placeholder="Enter card description (optional)"
                  rows="3"
                />
              </div>

              <div className="modal-buttons">
                <button type="button" onClick={() => setShowCardModal(false)} className="btn btn-secondary">
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary">
                  Create Card
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default BoardView;

// Benchmark/stack3-python/frontend/src/views/BoardView.vue
<template>
  <div class="board-view-container">
    <div v-if="loading" class="loading">Loading board...</div>
    <div v-else-if="error" class="error">{{ error }}</div>

    <div v-else-if="board" class="board-view">
      <div class="board-header">
        <div>
          <h2>{{ board.title }}</h2>
          <p class="board-description">{{ board.description }}</p>
        </div>
        <button @click="goBack" class="btn btn-secondary">
          ← Back to Boards
        </button>
      </div>

      <div class="lists-container">
        <div v-for="list in board.lists" :key="list.id" class="list">
          <div class="list-header">
            <h3>{{ list.title }}</h3>
            <button @click="deleteList(list.id)" class="btn-icon" title="Delete list">
              🗑️
            </button>
          </div>

          <div class="cards">
            <div
              v-for="card in list.cards"
              :key="card.id"
              class="card"
            >
              <div class="card-content">
                <h4>{{ card.title }}</h4>
                <p v-if="card.description">{{ card.description }}</p>
              </div>
              <button
                @click="deleteCard(list.id, card.id)"
                class="btn-icon card-delete"
                title="Delete card"
              >
                ✕
              </button>
            </div>
          </div>

          <button
            @click="showAddCard(list.id)"
            class="btn-add-card"
          >
            ➕ Add a card
          </button>

          <!-- Add Card Form -->
          <div v-if="addingCardToList === list.id" class="add-card-form">
            <input
              v-model="newCard.title"
              type="text"
              placeholder="Card title"
              @keyup.enter="createCard(list.id)"
              @keyup.esc="cancelAddCard"
            />
            <textarea
              v-model="newCard.description"
              placeholder="Description (optional)"
              rows="2"
            ></textarea>
            <div class="form-actions">
              <button @click="createCard(list.id)" class="btn btn-primary btn-sm">
                Add Card
              </button>
              <button @click="cancelAddCard" class="btn btn-secondary btn-sm">
                Cancel
              </button>
            </div>
          </div>
        </div>

        <!-- Add List Button -->
        <div class="list add-list">
          <button
            v-if="!showingAddList"
            @click="showingAddList = true"
            class="btn-add-list"
          >
            ➕ Add a list
          </button>

          <div v-else class="add-list-form">
            <input
              v-model="newList.title"
              type="text"
              placeholder="List title"
              @keyup.enter="createList"
              @keyup.esc="cancelAddList"
            />
            <div class="form-actions">
              <button @click="createList" class="btn btn-primary btn-sm">
                Add List
              </button>
              <button @click="cancelAddList" class="btn btn-secondary btn-sm">
                Cancel
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useBoardStore } from '../stores/boardStore'

const route = useRoute()
const router = useRouter()
const boardStore = useBoardStore()

const showingAddList = ref(false)
const addingCardToList = ref(null)

const newList = ref({ title: '' })
const newCard = ref({ title: '', description: '' })

const board = computed(() => boardStore.currentBoard)
const loading = computed(() => boardStore.loading)
const error = computed(() => boardStore.error)

onMounted(() => {
  boardStore.fetchBoard(route.params.id)
})

const goBack = () => {
  router.push('/')
}

const createList = async () => {
  if (!newList.value.title.trim()) return

  try {
    await boardStore.createList({
      title: newList.value.title,
      board: route.params.id,
      position: board.value.lists.length
    })
    newList.value.title = ''
    showingAddList.value = false
  } catch (error) {
    alert('Failed to create list')
  }
}

const cancelAddList = () => {
  newList.value.title = ''
  showingAddList.value = false
}

const deleteList = async (listId) => {
  if (confirm('Are you sure you want to delete this list?')) {
    try {
      await boardStore.deleteList(listId)
    } catch (error) {
      alert('Failed to delete list')
    }
  }
}

const showAddCard = (listId) => {
  addingCardToList.value = listId
}

const createCard = async (listId) => {
  if (!newCard.value.title.trim()) return

  try {
    const list = board.value.lists.find(l => l.id === listId)
    await boardStore.createCard({
      title: newCard.value.title,
      description: newCard.value.description,
      list: listId,
      position: list.cards.length
    })
    newCard.value = { title: '', description: '' }
    addingCardToList.value = null
  } catch (error) {
    alert('Failed to create card')
  }
}

const cancelAddCard = () => {
  newCard.value = { title: '', description: '' }
  addingCardToList.value = null
}

const deleteCard = async (listId, cardId) => {
  if (confirm('Are you sure you want to delete this card?')) {
    try {
      await boardStore.deleteCard(listId, cardId)
    } catch (error) {
      alert('Failed to delete card')
    }
  }
}
</script>

<style scoped>
.board-view-container {
  min-height: calc(100vh - 180px);
  padding: 2rem;
}

.board-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 2rem;
}

.board-header h2 {
  font-size: 2rem;
  color: #333;
  margin-bottom: 0.5rem;
}

.board-description {
  color: #666;
}

.lists-container {
  display: flex;
  gap: 1.5rem;
  overflow-x: auto;
  padding-bottom: 2rem;
}

.list {
  background: #ebecf0;
  border-radius: 8px;
  padding: 1rem;
  min-width: 300px;
  max-width: 300px;
  flex-shrink: 0;
  max-height: calc(100vh - 300px);
  display: flex;
  flex-direction: column;
}

.list-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}

.list-header h3 {
  font-size: 1.1rem;
  color: #333;
}

.cards {
  flex: 1;
  overflow-y: auto;
  margin-bottom: 1rem;
}

.card {
  background: white;
  border-radius: 6px;
  padding: 0.75rem;
  margin-bottom: 0.75rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  cursor: pointer;
  transition: transform 0.2s, box-shadow 0.2s;
  position: relative;
}

.card:hover {
  transform: translateY(-2px);
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.15);
}

.card-content h4 {
  font-size: 0.95rem;
  margin-bottom: 0.25rem;
  color: #333;
}

.card-content p {
  font-size: 0.85rem;
  color: #666;
  margin: 0;
}

.card-delete {
  position: absolute;
  top: 0.5rem;
  right: 0.5rem;
  opacity: 0;
  transition: opacity 0.2s;
}

.card:hover .card-delete {
  opacity: 0.6;
}

.card-delete:hover {
  opacity: 1 !important;
}

.btn-add-card {
  width: 100%;
  padding: 0.75rem;
  background: transparent;
  border: none;
  border-radius: 6px;
  color: #5e6c84;
  cursor: pointer;
  text-align: left;
  transition: background-color 0.2s;
}

.btn-add-card:hover {
  background: rgba(9, 30, 66, 0.08);
}

.add-list {
  background: rgba(255, 255, 255, 0.24);
  display: flex;
  align-items: flex-start;
}

.btn-add-list {
  width: 100%;
  padding: 0.75rem;
  background: transparent;
  border: none;
  color: white;
  cursor: pointer;
  text-align: left;
  border-radius: 6px;
  transition: background-color 0.2s;
}

.btn-add-list:hover {
  background: rgba(255, 255, 255, 0.16);
}

.add-card-form,
.add-list-form {
  background: white;
  padding: 0.75rem;
  border-radius: 6px;
}

.add-card-form input,
.add-card-form textarea,
.add-list-form input {
  width: 100%;
  padding: 0.5rem;
  border: 1px solid #ddd;
  border-radius: 4px;
  margin-bottom: 0.5rem;
  font-size: 0.9rem;
}

.form-actions {
  display: flex;
  gap: 0.5rem;
}

.btn {
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 6px;
  font-size: 1rem;
  cursor: pointer;
  transition: background-color 0.2s;
}

.btn-sm {
  padding: 0.5rem 1rem;
  font-size: 0.9rem;
}

.btn-primary {
  background: #667eea;
  color: white;
}

.btn-primary:hover {
  background: #5568d3;
}

.btn-secondary {
  background: #e0e0e0;
  color: #333;
}

.btn-secondary:hover {
  background: #d0d0d0;
}

.btn-icon {
  background: none;
  border: none;
  cursor: pointer;
  font-size: 1rem;
  opacity: 0.6;
  transition: opacity 0.2s;
}

.btn-icon:hover {
  opacity: 1;
}

.loading,
.error {
  text-align: center;
  padding: 3rem;
  font-size: 1.1rem;
}

.error {
  color: #e74c3c;
}
</style>
